"use strict";
exports.__esModule = true;
var express = require("express");
var wallet = require("./controllers/wallet");
var transaction = require("./controllers/transaction");
var bodyParser = require("body-parser");
var dbController = require("./controllers/dbController");
var jwtController = require("./controllers/jwtcontroller");
var middleware = require("./middleware");
var exchange = require("./controllers/exchangeController");
var app = express();
app.set("port", 3000);
app.use(bodyParser.json());
app.get("/transactions", transaction.transactions);
app.get("/transaction/:id/", transaction.getTransaction);
app.post("/transaction", middleware.verifyToken, transaction.addTransaction);
app["delete"]("/transaction/:id", middleware.verifyToken, transaction.delTransaction);
app.put("/transaction/:id/:execute*?", middleware.verifyToken, transaction.updateTransaction);
app.get("/wallets", wallet.wallets);
app.get("/wallet/:id/:transactions*?", wallet.getWallet);
app.post("/wallet", middleware.verifyToken, wallet.addWallet);
app["delete"]("/wallet/:id", middleware.verifyToken, wallet.delWallet);
app.put("/wallet/:id", middleware.verifyToken, wallet.updateWallet);
app.get("/initialise", dbController.initialise);
app.get("/drop", dbController.drop);
app.get("/getToken", jwtController.genToken);
app.get("/exchange", exchange.getRates);
app.listen(app.get("port"), function () {
    console.log("server running on port %d", app.get("port"));
});
